### PR TITLE
groovy: enable grab for system class loader

### PR DESCRIPTION
**Pull request by MykolaGolubyev**

### CODE REVIEW

**Comment by MykolaGolubyev** [comment]
@tsiq-karold I wonder if that was the issue you once faced

**Comment by tsiq-karold** [comment]
> @tsiq-karold I wonder if that was the issue you once faced

What did you observe that led you to this change?

**Comment by MykolaGolubyev** [comment]
I was trying to add jdbc driver with grab and was getting by stranger errors. 
‘’’
@GrabConfig(systemClassLoader=true)
@Grab(group='mysql', module='mysql-connector-java', version='5.1.6'
‘’’

**Comment by MykolaGolubyev** [comment]
I was trying to add jdbc driver with grab and was getting by stranger errors. 
‘’’
@GrabConfig(systemClassLoader=true)
@Grab(group='mysql', module='mysql-connector-java', version='5.1.6'
‘’’

**Comment by tsiq-clemens** [comment]
sorry, late to the party. 
I had trouble with some Grabs with groovy versions 2.5.x, I believe, which came down (deep down) to the class loader. The details escape me now. What version of groovy are you testing with?

**Pull request merged**
